feat: finish home screen design and implementation.
Marco-Nagy/flowery_app pull request #11
Opened 2024-11-20 15:50 UTC by somaya-mahmoud

feat : home screen design and implementation.

2024-11-20 18:20 UTC, Marco-Nagy requested changes
معلش يا باشمهندسة مضطرين نعدل ال 3 Apis اللى فى ال home  ب Api واحدة فيهم ال 3 list مع بعض اسهل
و الداتا متضافة فيهم

2024-11-20 18:20 UTC, Marco-Nagy commented on lib/core/networking/api/api_manager.dart
> +Future<BestSellerResponseModelEntity> getBestSellers();
Now You Can replace the three Apis with home
with Get Home

2024-11-20 19:13 UTC, haidyhesham95 approved these changes

2024-11-21 14:56 UTC, YasmeenGad approved these changes

2024-11-23 18:05 UTC, closed without merging