Feature ( Categories ): Ecom-13-categories
Marco-Nagy/flowery_app pull request #12
Opened 2024-11-21 02:38 UTC by YasmeenGad

+ add method of get all categories in API manager 
+ create  get all categories response DTO for fetched categories
+ add API constant of all categories

2024-11-21 02:47 UTC, Marco-Nagy approved these changes

2024-11-21 02:47 UTC, Marco-Nagy commented on lib/features/categories/data/data_sources/categories_online_data_source.dart
Empty File

2024-11-21 03:01 UTC, Marco-Nagy approved these changes

2024-11-21 03:13 UTC, Marco-Nagy requested changes

2024-11-21 03:13 UTC, Marco-Nagy commented on lib/features/categories/data/repositories/categories_repo_impl.dart
This function Without body ???

2024-11-21 03:16 UTC, YasmeenGad commented on lib/features/categories/data/data_sources/categories_online_data_source.dart
يا بشمهندس حضرتك قولت اي commitحتى لو صغيره نعملها على طول pr انا لسه مخلصتش باقي ال impl في ال  pr دي

2024-11-21 13:09 UTC, somaya-mahmoud approved these changes

2024-11-21 15:01 UTC, haidyhesham95 approved these changes

2024-11-22 03:10 UTC, Marco-Nagy approved these changes

2024-11-22 03:10 UTC, merged