Feature/home ecom 8
Marco-Nagy/flowery_app pull request #3
Opened 2024-11-17 10:20 UTC by somaya-mahmoud

feat : add home screen design .

2024-11-17 10:45 UTC, Marco-Nagy requested changes
please refactor MyFonts Class with flowery app text style
 FontWeigt
 FontSize
 add images paths to AppImages Class and use it as static const

2024-11-17 10:45 UTC, Marco-Nagy commented on assets/images/deliver_to.png
this is Text not image 
please refactor it to text with the same font and size and color

2024-11-17 10:45 UTC, Marco-Nagy commented on assets/images/place.png
this is Text not image 
please refactor it to text with the same font and size and color

2024-11-17 10:45 UTC, Marco-Nagy commented on lib/features/home/presentation/screens/home_screen.dart
> +                    'assets/images/category.png',
please use AppImages class to store images path as static const

2024-11-17 10:45 UTC, Marco-Nagy commented on lib/features/home/presentation/screens/home_screen.dart
> +                    'assets/images/person.png',
please use AppImages class to store images path as static const

2024-11-17 10:45 UTC, Marco-Nagy commented on lib/features/home/presentation/tabs/cart_tab.dart
> +            style: TextStyle(
please use MyFonts class and use font style

2024-11-17 10:45 UTC, Marco-Nagy commented on lib/features/home/presentation/tabs/home_tab.dart
> +              'assets/images/logo.png',
please use AppImages class to store images path as static const

2024-11-17 10:45 UTC, Marco-Nagy commented on lib/features/home/presentation/tabs/profile_tab.dart
> +            style: TextStyle(
Please use Myfonts  and refactor it with app font styles

2024-11-17 15:14 UTC, Marco-Nagy approved these changes
عااااش اوى الله ينور يا هندسة 🙌

2024-11-17 15:21 UTC, somaya-mahmoud commented
fix : use app images class to store path of images , and Use MyFonts class with app font style.

2024-11-17 15:22 UTC, somaya-mahmoud commented
fix : use app images to store images path and use MyFonts class with flower app font style.

2024-11-17 15:24 UTC, Marco-Nagy approved these changes

2024-11-17 15:43 UTC, Marco-Nagy approved these changes

2024-11-18 03:09 UTC, haidyhesham95 approved these changes

2024-11-18 10:56 UTC, YasmeenGad approved these changes

2024-11-18 11:03 UTC, merged