Feature/ecom 34 profile main screen
Marco-Nagy/flowery_app pull request #36
Opened 2024-11-28 04:32 UTC by somaya-mahmoud

feat :  design profile main screen and logout dialog.
![designMain3](https://github.com/user-attachments/assets/bcebf9cc-b66d-4ec9-8ec5-e3130ef5de1c)
![desingMain1](https://github.com/user-attachments/assets/00ce8b76-107d-4b33-890d-243834ca44a0)
![designMain2](https://github.com/user-attachments/assets/3d2d710b-099d-40e3-80ce-cf25fc49e704)

2024-11-29 13:55 UTC, haidyhesham95 requested changes

2024-11-29 13:55 UTC, haidyhesham95 commented on lib/features/profile/presentation/widgets/custom_app_bar_of_profile_main_screen.dart
> +              Icons.notifications,
ال icon اللي في موجده غي فيجما خديها وحطيها هنا هنا gray اللي في فيجما بيضه

2024-11-29 13:55 UTC, haidyhesham95 commented on lib/features/profile/presentation/widgets/custom_app_bar_of_profile_main_screen.dart
> +              color: MyColors.gray,
شيلي ال color بس منها اعتقد هتظبط

2024-11-29 13:56 UTC, haidyhesham95 commented
عااااش يبشمهندسه ❤️

2024-11-29 18:48 UTC, Marco-Nagy requested changes
محتاجين نعدل ال comments بس

2024-11-29 18:48 UTC, Marco-Nagy commented on assets/images/switch.png
ده switch button بيتعمل مش image

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/data/data_sources/impl/profile_online_data_source_impl.dart
>        var response = await _apiManager.getLoggedUserData("Bearer $token");
انتى مككرة السطر ده ليه؟

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/viewModel/profile_view_model_cubit.dart
> +        print('returnedData : ${result.data}');
يا ريت نستخدم debug print

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/views/profile_main_screen.dart
> +                      'assets/images/terms_conditions.png',
بلاااااش hard code يا سمية 
استخدمى Asset Class

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/views/profile_main_screen.dart
> +                          'assets/images/drop_down_arrow.png',
The same

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/views/profile_main_screen.dart
> +                      'assets/images/location.png',
The same

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/views/profile_main_screen.dart
> +                          'assets/images/drop_down_arrow.png',
👎

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/views/profile_main_screen.dart
> +                          child: Image.asset('assets/images/language.png')),
👎

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/views/profile_main_screen.dart
> +                          'assets/images/logout.png',
👎

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/widgets/custom_main_profile_data.dart
> +                context: context,
بنشيل ال loading من هنا و بنحطها فى البيلدر  App Loader

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/widgets/custom_main_profile_data.dart
> +              print('name is : ${state.data.user!.firstName}');
debug print

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/widgets/custom_main_profile_data.dart
> +         if(state is GetLoggedUserDataSuccess){
قولنا هنستخدم switch case بدل if else

2024-11-29 18:48 UTC, Marco-Nagy commented on lib/features/profile/presentation/widgets/custom_main_profile_data.dart
> +         if(state is GetLoggedUserDataSuccess){
نحط ال code bloc فى widget

2024-11-29 21:18 UTC, somaya-mahmoud commented on lib/features/profile/data/data_sources/impl/profile_online_data_source_impl.dart
>        var response = await _apiManager.getLoggedUserData("Bearer $token");
مش متكرر عندى فى الكود .

2024-11-29 21:20 UTC, somaya-mahmoud commented on lib/features/profile/presentation/widgets/custom_app_bar_of_profile_main_screen.dart
> +              Icons.notifications,
يا جماعة والله اللى موجودة في فيجما موجودة ك asset عليها رقم 3 مش موجودة ك ايقون لوحدها وال notification هنحتاجها معانا ال sprint الجايه تكون متهندلة انها ترجع عدد ال notification وبردو عشان تكون نفس الديزاين نزلتها ك svg واستخدمتها وبردو شكلها مظبطش طب اعمل ايه

2024-11-29 21:21 UTC, somaya-mahmoud commented on lib/features/profile/presentation/widgets/custom_app_bar_of_profile_main_screen.dart
> +              color: MyColors.gray,
ولا اى اندهاش سواء اتشال أو موجود .

2024-11-29 22:45 UTC, haidyhesham95 commented on lib/features/profile/presentation/widgets/custom_app_bar_of_profile_main_screen.dart
> +              Icons.notifications,
هبقي اشوفها لما الكود يترفع

2024-11-29 22:46 UTC, haidyhesham95 approved these changes

2024-11-30 00:37 UTC, YasmeenGad approved these changes

2024-11-30 06:16 UTC, haidyhesham95 approved these changes

2024-11-30 18:31 UTC, Marco-Nagy approved these changes

2024-11-30 18:32 UTC, merged