feat: register
Marco-Nagy/flowery_app pull request #4
Opened 2024-11-17 23:08 UTC by haidyhesham95

feat: implement signup UI and integrate with API
+added register ui 
![WhatsApp Image 2024-11-17 at 23 38 55_9e7b6eca](https://github.com/user-attachments/assets/08e25dc6-f2e6-436f-b9c5-bc2c94322cb4)

2024-11-17 23:53 UTC, Marco-Nagy requested changes

2024-11-17 23:53 UTC, Marco-Nagy commented on lib/core/networking/api_execute.dart
this class name changed to Data class 

i suggests update project before pr

2024-11-17 23:53 UTC, Marco-Nagy commented on lib/core/networking/common/api_result.dart
this class name changed to Data class

i suggests update project before pr

2024-11-17 23:53 UTC, Marco-Nagy commented on lib/features/auth/presentation/signup/view_model/signup_cubit.dart
> +  final AuthUseCase _authUseCase;
its not best practice to declare  TextEditingController

2024-11-17 23:53 UTC, Marco-Nagy commented on lib/features/auth/presentation/signup/view_model/signup_cubit.dart
> +  final AuthUseCase _authUseCase;
i suggest refactoring this using Flutter hooks package 
i preferer to vote on this step or refactor it with best practice for declaration

2024-11-17 23:53 UTC, Marco-Nagy commented on lib/features/auth/presentation/signup/view_model/signup_state.dart
> +sealed class SignupAction {}
please separate Sign Up states and sign up action each one in dart file

2024-11-18 10:51 UTC, somaya-mahmoud approved these changes

2024-11-18 11:01 UTC, YasmeenGad approved these changes

2024-11-18 19:00 UTC, Marco-Nagy approved these changes

2024-11-18 19:00 UTC, merged