fix : solve conflict show when merge
Marco-Nagy/flowery_app pull request #43
Opened 2024-11-30 22:56 UTC by haidyhesham95

- solve conflict and warning

2024-11-30 23:02 UTC, Marco-Nagy requested changes
نرجع بس ال container

2024-11-30 23:02 UTC, Marco-Nagy commented on lib/features/generic/presentation/generic_item_by_product/widget/generic_build_item.dart
> +          SizedBox(
ده المفروض يفضل container عشان مايضربش مع الanimated_add_to_cart

2024-11-30 23:23 UTC, somaya-mahmoud approved these changes

2024-12-01 01:08 UTC, somaya-mahmoud approved these changes

2024-12-01 01:16 UTC, Marco-Nagy approved these changes

2024-12-01 01:16 UTC, merged