Testing: Test Profile view model functions
Marco-Nagy/flowery_app pull request #49
Opened 2024-12-05 01:53 UTC by YasmeenGad

2024-12-05 02:08 UTC, Marco-Nagy requested changes
هرجع تعديل ال pubspec yamel

2024-12-05 02:08 UTC, Marco-Nagy commented on pubspec.yaml
رجعى التعديل ده معلش عشا لسة مظبطه فى الcommit اللى فات

2024-12-05 02:08 UTC, Marco-Nagy commented on test/features/profile/presentation/viewModel/profile_view_model_cubit_test.dart
> +
فى فكرة كويسة لل dummy data
هنعمل class of static objects of dummy data and call it every were

2024-12-05 10:40 UTC, haidyhesham95 commented
ال linting محتاج يتظبط

2024-12-05 20:16 UTC, YasmeenGad commented on pubspec.yaml
متكرر عندي لازم يتشال

2024-12-05 20:17 UTC, YasmeenGad commented on test/features/profile/presentation/viewModel/profile_view_model_cubit_test.dart
> +
اوكي اعمل approve لل pr وان شاء الله من ال pr الجايه هستخدمها😂

2024-12-05 20:17 UTC, YasmeenGad commented
> ال linting محتاج يتظبط

يعني ايه الكلام ده؟

2024-12-08 22:02 UTC, Marco-Nagy commented
يعنى نrun flutter analyze
ونعدل الفايلات اللى فيها ايررور ونشيل الحاجات اللى طلعت هنا او نمشى زى الايررور ما هو طالب منك هنا
![image](https://github.com/user-attachments/assets/f3cc948b-8d0c-4132-8e54-2375d55ffe15)

2024-12-09 20:58 UTC, somaya-mahmoud approved these changes

2024-12-09 21:00 UTC, Marco-Nagy approved these changes

2024-12-09 21:00 UTC, merged