Feature/ecom 39 user addresses
Marco-Nagy/flowery_app pull request #50
Opened 2024-12-05 03:56 UTC by somaya-mahmoud

feat : add design and implementation for saved address screen and design add address screen.
![saved address](https://github.com/user-attachments/assets/4faadca5-7530-4e7f-b735-247aea3a87f4)
![add address](https://github.com/user-attachments/assets/02896d81-65f2-4585-95b0-aacebcb11ec9)

2024-12-08 21:50 UTC, Marco-Nagy requested changes
الله ينور يا سمية عااااش اوى بجد 👏 👏👏👏
بس محتاجين نعدل الحاجات اللى فى الكومنتات

2024-12-08 21:50 UTC, Marco-Nagy commented on lib/features/address/presentation/widgets/custom_card_item.dart
> +                                      'Cairo',
المفروض هنا بنرجع داتا من الaddress
انا سالت باشمهندس محمد فى النقطة دى انهاردة فى الgrooming و قالى نرجع الstreetName

2024-12-08 21:50 UTC, Marco-Nagy commented on lib/features/cart/presentation/screens/cart_view.dart
> +            );
انا عدلت فى السكرينة دى فياريت نشيلها من الcommit ده عشان مايحصلش conflict

2024-12-08 21:50 UTC, Marco-Nagy commented on lib/features/cart/presentation/widgets/cart_view_body.dart
> +                       ),
نفس الكلام انا معدل هنا

2024-12-08 21:50 UTC, Marco-Nagy commented on lib/features/profile/presentation/widgets/custom_picture_main_screen.dart
> +           case ChangePasswordSuccess():
نفس الكلام احنا معدلين هنا

2024-12-08 22:12 UTC, Marco-Nagy commented
محتاجين نحل الconflicts دى الاول
ممكن ندخل meeting اوريكى ازاى

2024-12-09 20:35 UTC, Marco-Nagy approved these changes

2024-12-10 20:15 UTC, haidyhesham95 approved these changes

2024-12-10 23:33 UTC, merged