Origin/feature/profile/ecom 40 terms and conditions
Marco-Nagy/flowery_app pull request #51
Opened 2024-12-08 21:10 UTC by haidyhesham95

- feat: create sample TermsAndConditionsPage

![WhatsApp Image 2024-12-08 at 23 09 19_1c9aca83](https://github.com/user-attachments/assets/ef34bfac-d2fa-4f48-9fea-54e68fb11636)

2024-12-08 21:54 UTC, Marco-Nagy requested changes
الله ينور يا هايدى 👏👏👏👏
محتاجين نشيل التعديلات من ال pubspec بس

2024-12-08 21:54 UTC, Marco-Nagy commented on pubspec.yaml
> -
محتاجين نشيل التعديلات اللى هنا عشان مايحصلش conflicts و المفروض بعد كدة نعمل update من الdevelopment و الكللام ده كله بيتظبط

2024-12-08 22:04 UTC, haidyhesham95 commented on pubspec.yaml
> -
هو كل الفايلات دي من الميرج انا ملعبتش فيهم هما بيتعملهم push اللي باخده من الميرج اللي عدلته هو الكومنت ده fix : The showSnackBar in custom_main_profile_data.dart. من كام يوم. وده بس feat: create sample TermsAndConditionsPage

2024-12-08 22:09 UTC, Marco-Nagy commented on pubspec.yaml
> -
خلاص هعمل merge و لو ضرب نبقى نتصرف
بس محتاجين نسال نتفادى الموضوع ده ازاى

2024-12-08 22:10 UTC, Marco-Nagy approved these changes
خلاص هعمل merge و لو ضرب نبقى نتصرف
بس محتاجين نسال نتفادى الموضوع ده ازاى

2024-12-08 22:19 UTC, haidyhesham95 commented
> خلاص هعمل merge و لو ضرب نبقى نتصرف بس محتاجين نسال نتفادى الموضوع ده ازاى

بجد اه اصل المفروض ميعملش push اللي انا اصلا باخده ميرج لما بقف علي ال development

2024-12-09 20:57 UTC, somaya-mahmoud approved these changes

2024-12-09 20:59 UTC, merged