Feat: ECOM-41-About-App
Marco-Nagy/flowery_app pull request #53
Opened 2024-12-09 21:31 UTC by YasmeenGad

+ 
![WhatsApp Image 2024-12-09 at 11 26 15 PM](https://github.com/user-attachments/assets/bc5f20aa-57f6-43ad-8920-d4a02b8bc84e)

https://github.com/user-attachments/assets/6e589cc5-317a-4348-a926-fe91d9017e3b

2024-12-09 22:25 UTC, Marco-Nagy requested changes
محتاجين السطور اللى مهيشينها نرجعها تانى و بعدين نعمل كوميت و بوش

2024-12-09 22:25 UTC, Marco-Nagy commented on analysis_options.yaml
> +# include: package:flutter_lints/flutter.yaml
ماينفعش نقفل ال linting
محتاجين نرجع ال line ده

2024-12-09 22:25 UTC, Marco-Nagy commented on lib/features/about_app/presentation/views/about_app_view.dart
> +                        FadeInUp(
فكرة حلوة جدا

2024-12-09 22:25 UTC, Marco-Nagy commented on lib/flowery_ecommerce.dart
> +              initialRoute: AppRoutes.aboutAppView,
محتاجين نرجع الline ده

2024-12-10 20:05 UTC, Marco-Nagy approved these changes

2024-12-10 20:07 UTC, haidyhesham95 approved these changes

2024-12-10 22:35 UTC, merged