Feature/Ecom-38-address-details
Marco-Nagy/flowery_app pull request #54
Opened 2024-12-10 23:13 UTC by YasmeenGad

+ Create Dto of add address feature
+ create domain entities

2024-12-10 23:33 UTC, Marco-Nagy requested changes
محتاجين نهندل اللينتينج قبل الميرج
تانى حاجة نشيل ال مش محتاجين fromJson هنا 😄

2024-12-10 23:33 UTC, Marco-Nagy commented on lib/features/address_details/data/models/request/add_address_request_dto.dart
> +      _$AddAddressRequestDtoFromJson(json);
مش محتاجين fromJson هنا

2024-12-10 23:33 UTC, Marco-Nagy commented on lib/features/address_details/data/models/response/add_address_response_dto.dart
> +  factory AddAddressResponseDtoAddress.fromJson(Map<String, dynamic> json) =>
مش محتاجين fromJson هنا

2024-12-11 00:03 UTC, Marco-Nagy approved these changes

2024-12-11 00:09 UTC, haidyhesham95 approved these changes

2024-12-11 00:24 UTC, haidyhesham95 approved these changes

2024-12-11 01:01 UTC, merged