feature/ECOM-47-Receive-Notification
Marco-Nagy/flowery_app pull request #79
Opened 2024-12-16 00:02 UTC by YasmeenGad

+ Integrated Firebase Cloud Messaging (FCM) to handle receiving notifications
![WhatsApp Image 2024-12-16 at 1 52 36 AM](https://github.com/user-attachments/assets/e9f8929a-ffdb-4c3e-b20e-2e7ca637a4e6)

2024-12-16 01:31 UTC, Marco-Nagy approved these changes

2024-12-16 14:04 UTC, haidyhesham95 reviewed
عاش اووي اوووي , هو بس ال linting يتظبط

2024-12-21 19:53 UTC, Marco-Nagy requested changes

2024-12-21 19:53 UTC, Marco-Nagy commented on lib/core/services/firebase_notification/firebase_cloud_messaging.dart
> +    debugPrint("Handling a background message: ${message.notification}");
محتاجين نهندل ال navigation to notification screen

2024-12-21 20:21 UTC, Marwan2595 requested changes
1.  Separate the order list itemBuilder in a separate widget (ex: OrderCard)
2. put the code responsible for navigation (when tapping on the notification ) in a separate function and use this function in all cases (foreground, background, and terminated).
3. show notifications on the foreground 
4. handle navigation in all cases

2024-12-25 22:51 UTC, Marco-Nagy approved these changes

2024-12-25 22:52 UTC, merged