feature/ECOM-31-Github-Actions-Create-Validate-PR-title-Action
Marco-Nagy/flowery_app pull request #86
Opened 2024-12-16 19:16 UTC by Marco-Nagy

2024-12-19 01:13 UTC, YasmeenGad requested changes, later dismissed

2024-12-19 01:13 UTC, YasmeenGad commented on .github/workflows/validate-pr-title.yml
> +            exit 1
write validation pattern in separated file to satisfy clean code principle

2024-12-20 18:29 UTC, haidyhesham95 approved these changes

2024-12-21 19:40 UTC, Marwan2595 approved these changes

2024-12-21 19:43 UTC, merged