feat: Add LocationHelper for managing user location and permissions
Marco-Nagy/flowery_app pull request #87
Opened 2024-12-18 21:45 UTC by haidyhesham95

- Implemented saving and retrieving location using SharedPreferences.
- Added methods to check location services and request permissions.
- Enhanced error handling and fallback for location-related operations.
- Included geolocation and reverse geocoding functionality.           
                                                                                                      
![WhatsApp Image 2024-12-18 at 23 31 38_712c50a9](https://github.com/user-attachments/assets/378ddc7a-d6e1-49e3-a8b5-52e96b67565b)
![WhatsApp Image 2024-12-18 at 23 31 38_adea7265](https://github.com/user-attachments/assets/ad49f724-c867-4cec-8946-3e95dc38205e)
![WhatsApp Image 2024-12-18 at 23 31 38_4e566cfd](https://github.com/user-attachments/assets/dcdfd598-204b-4e4a-905e-8b7ac7e501a3)
![WhatsApp Image 2024-12-18 at 23 31 38_f34dfe1f](https://github.com/user-attachments/assets/07ad8cc6-9bf3-469a-989d-a0fe171a1adf)

2024-12-19 02:23 UTC, Marco-Nagy requested changes
عاااش يا هيدى 
شغل عالى عالى الصراحة
بس محتاجين نهندل ال functions فى ال view model افضل ك clean code
و اعتقد محتاجين نضيف comments as documentation at location helper class and location widget

2024-12-19 02:23 UTC, Marco-Nagy commented on lib/core/services/shared_preference/location_helper.dart
> +      String? token = await offlineDataSource.getToken();
you don't need to concatenate location kye with token

i prefer just save location value with location key

2024-12-19 02:23 UTC, Marco-Nagy commented on lib/features/home_screen/presentation/widgets/location _widget.dart
> +
please refactor set state functions at cart view model

2024-12-20 21:48 UTC, Marco-Nagy requested changes
محتاجين نعدل حاجات بسيطة بس الله ينور شغل عاالى جدا 👏  👏  👏  👏  👏  👏

2024-12-20 21:48 UTC, Marco-Nagy commented on lib/features/auth/presentation/login/viewModel/login_view_model_cubit.dart
> +    }
التعديل ده محتاجين نعمله فى function منفصله و نعملها call فى ال login bloc listener at loading case

2024-12-20 21:48 UTC, Marco-Nagy commented on lib/features/cart/presentation/widgets/cart_view_body.dart
> +    setState(() {
محتاجين ننقل الfunction دى لل view model و نعملها call هنا بس

2024-12-20 21:48 UTC, Marco-Nagy commented on lib/features/home_screen/presentation/widgets/location _widget.dart
> +            return Center(
الاحسن return awesome snackbar loading

2024-12-20 23:50 UTC, haidyhesham95 commented on lib/features/home_screen/presentation/widgets/location _widget.dart
> +            return Center(
مش هتبقي حلوه كده احسن

2024-12-21 01:21 UTC, haidyhesham95 commented on lib/features/auth/presentation/login/viewModel/login_view_model_cubit.dart
> +    }
عدلته

2024-12-21 01:21 UTC, haidyhesham95 commented on lib/features/cart/presentation/widgets/cart_view_body.dart
> +    setState(() {
عدلته

2024-12-21 20:38 UTC, Marwan2595 approved these changes

2024-12-21 20:46 UTC, Marco-Nagy approved these changes

2024-12-21 20:46 UTC, merged