Feature/ecom-52-search/Implement Search Functionality
Marco-Nagy/flowery_app pull request #89
Opened 2024-12-20 20:49 UTC by YasmeenGad

+ The search functionality has been added to the app, supporting loading, success, and no results states. If no products are found, a "No products found" message is displayed with an illustration image. The search interface has been enhanced with a custom search bar, and the results are displayed in a grid of product cards.

![WhatsApp Image 2024-12-20 at 10 47 16 PM](https://github.com/user-attachments/assets/138dfd12-0d2d-4eb4-a2b1-4819d6cca77f)

![WhatsApp Image 2024-12-20 at 10 47 15 PM](https://github.com/user-attachments/assets/0809bddf-8f47-42d6-904b-02e88cd0cee2)

![WhatsApp Image 2024-12-20 at 10 47 15 PM (2)](https://github.com/user-attachments/assets/73486ff0-376b-43de-99e6-f0c4da131dee)

2024-12-20 21:38 UTC, Marco-Nagy requested changes
كان ممكن نعدل الفانكشن getAllProducts و نضيفلها ال query ولكن مش required بس

2024-12-20 21:38 UTC, Marco-Nagy commented on lib/core/networking/api/api_manager.dart
> +  Future<SearchResponseDto> searchProducts(@Query("keyword") String keyword);
i think you must have to just update getAllProducts( ) function with a nullable query

2024-12-20 22:55 UTC, YasmeenGad commented on lib/core/networking/api/api_manager.dart
> +  Future<SearchResponseDto> searchProducts(@Query("keyword") String keyword);
عملت api جديد عادي مش مشكله عدوها بقى والله عملت التاسك وانا مضغوطه في مذاكرة المنهج

2024-12-20 22:57 UTC, Marco-Nagy commented on lib/core/networking/api/api_manager.dart
> +  Future<SearchResponseDto> searchProducts(@Query("keyword") String keyword);
الله ينور مقولناش حاجة بس كان ممكن تحليها بسطرين بس وسط الزنقة دى مش اكتر 
انا صعبان عليا مجهودك بس

2024-12-28 19:15 UTC, haidyhesham95 approved these changes

2025-01-14 14:57 UTC, closed without merging